### ISSUE TITLE
Dashboard Add Feed Calculator doesn't work

### ISSUE THREAD

**Issue by networkempire** [themezoom/social-explosion-dashboard#9] opened 2015-06-28 03:26 UTC
calculator for feed doesn't work:  http://screencast.com/t/jl8enH2CgCyW

**Comment by spurton** [comment] 2015-07-13 20:33
Maybe the feed wasn't parsable at the time? I can get it to load: https://dl.dropboxusercontent.com/u/6988350/Screen%20Shot%202015-07-13%20at%201.32.13%20PM.png

**Comment by spurton** [comment] 2015-07-27 18:33
Since I can't reproduce, I am closing this

**Closed as completed by spurton** 2015-07-27 18:33 UTC
